@startmindmap
*[#lightblue] @CCCP.education.COM

**:digital artisan
agence;


***[#lightgreen] buts
****_  augmenter CA
****_  améliorer UX
*** services
**** site
**** mobile
**** specific
*** about
*** contact form
*** portfolio showroom
** portfolio
** blog
** vcard
** phonebackup

left side

** belief
** books
** cadrage
** video formation selection
** toodoo
** Today I Land (TIL)
** design pattern quizz
**[#FFBBCC] 5 projects
***_ realestate
***_ resto
***_ portfolio
***_ ecommerce
***_ digital agency
**[#Orange] draft
*** hairdress
****_:mobile app
      filtre foto;

@endmindmap